name: "tagged-release"

on:
  push:
    tags:
      - "*.*"

jobs:
  on-main-branch-check:
    runs-on: ubuntu-latest
    outputs:
      on_main: ${{ steps.contains_tag.outputs.retval }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: rickstaa/action-contains-tag@v1.2.9
        id: contains_tag
        with:
          reference: "master"
          tag: "${{ github.ref }}"
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    needs: on-main-branch-check
    if: ${{ needs.on-main-branch-check.outputs.on_main == 'true' }}
    steps:

      # --- from main.yml ---
      - uses: actions/checkout@v4
      - name: Set up JDK 1.17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew -PbuildNo=${{ github.run_number }} remapJar
      # --- from main.yml ---

      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/libs/*.jar
